contributr/contriblog/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.BlogIndex.as_view(), name="index"),
    url(r'^tags/(?P<tag>\S+)$', views.TagDetail.as_view(), name="tag_detail"),
    url(r'^post/(?P<slug>\S+)$', views.BlogDetail.as_view(), name="detail"),
    ]

contributr/contributr/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(
        template_name='contributr/index.html'), name="home"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include("contriblog.urls", namespace="blog"))
]

contributr/contriblog/models.py
from django.db import models

from django.core.urlresolvers import reverse

# Tag class
class Tag(models.Model):
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.slug

# Custom queryset manager that only displays posts that have publish set to true.
class PostQuerySet(models.QuerySet):

    def published(self):
        return self.filter(publish=True)


class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('auth.User')
    body = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    edited_date = models.DateTimeField(auto_now=True)
    publish = models.BooleanField(default=False)
    slug = models.SlugField(max_length=200, unique=True)
    tags = models.ManyToManyField(Tag)

    objects = PostQuerySet.as_manager()

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Blog post"
        verbose_name_plural = "Blog posts"
        ordering = ["-created_date"]

contributr/contriblog/views.py
from django.views import generic

from . import models


# Generic view that lists all blog posts that has publish set to true.
class BlogIndex(generic.ListView):
    queryset = models.Post.objects.published()
    template_name = "contriblog/index.html"


# Generic view that displays each post.
class BlogDetail(generic.DetailView):
    model = models.Post
    template_name = "contriblog/detail.html"

# Generic view that lists every post with selected tag.
class TagDetail(generic.DetailView):
    model = models.Tag
    template_name = "contriblog/tag.html"
    slug_url_kwarg = "tag"

contributr/contriblog/templates/contriblog/detail.html
{% extends 'base.html' %}
{% load markdown_deux_tags %}

{% block head_title %}Contributr blog{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-10">
    <div class="page-header">
      <h1>{{ object.title }}</h1>
    </div>

    <p class="text-muted">
        created on {{ object.created_date|date }}, by {{ object.author }} | Tagged under
        {% for tag in object.tags.all %}
            <a href="{% url "blog:tag_detail" tag=tag.slug %}">{{ tag.slug }}</a>{% if not forloop.last %},{% endif %}
        {% endfor %}
    </p>

    <p>{{ object.body|markdown }}</p>

  </div>
</div>
{% endblock %}

contributr/contriblog/templates/contriblog/index.html
{% extends 'base.html' %}
{% load markdown_deux_tags %}

{% block head_title %}Contributr blog{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-10">
    <div class="page-header">
      <h1>Contributr blog</h1>
    </div>
  {% for object in object_list %}
    <h3><a href="{% url "blog:detail" slug=object.slug %}">{{ object.title }}</a></h3>
    
    <p class="text-muted">
        created on {{ object.created_date|date }}, by {{ object.author }} | Tagged under
        {% for tag in object.tags.all %}
            <a href="{% url "blog:tag_detail" tag=tag.slug %}">{{ tag.slug }}</a>{% if not forloop.last %},{% endif %}
        {% endfor %}
    </p>

    <p>{{ object.body|markdown }}</p>
  </div>
</div>
{% endfor %}
{% endblock %}

contributr/contriblog/templates/contriblog/tag.html
{% extends "base.html" %}
{% block content %}
  <div class="post">
    <h2>Tagged under {{ object.slug }}</h2>
    <ul>
      {% for entry in object.post_set.all %}
        <li><a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a></li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

contributr/contributr/templates/base.html
{% load staticfiles %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block head_title %}Contributr{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="{% static 'img/favicons/apple-touch-icon.png' %}">

        {% block css %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        {% endblock %}

        {% block modernizr %}
        <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
        {% endblock %}
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    {% block navbar %}
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">Contributr</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{%url 'blog:index' %}">Blog</a></li>
            <li><a href="https://github.com/Djenesis/contributr">GitHub</a></li>
          </ul>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>
    {% endblock%}

    <!-- Main content block -->
    <div class="container">
    {% block content %}{% endblock %}
    </div>


      {% block footer %}
      <footer class="footer">
      <div class="container">
        <p class="text-muted">&copy; <a href="https://github.com/Djenesis">Djenesis</a> 2015</p>
      </div>
      </footer>
      {% endblock %}
    </div>
    <!-- /container -->
    {% block javascript %}
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="static/js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

        <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>

        <script src="{% static 'js/main.js' %}"></script>
    {% endblock %}

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
    </body>
</html>

contributr/contributr/templates/contributr/index.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron">
        <h1>Contributr</h1>
        <p>An online tool for programmers to find projects they can contribute to and project maintainers to find contributors.</p>
      </div>

{% endblock %}